<<<<<<< HEAD
# Generated by Django 4.2.11 on 2024-05-10 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holiday', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='payment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('card_name', models.TextField(blank=True, null=True)),
                ('card_no', models.TextField(blank=True, null=True)),
                ('date', models.TextField(blank=True, null=True)),
                ('cvv', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'payment',
                'managed': False,
            },
        ),
    ]
=======
# Generated by Django 4.2.11 on 2024-05-10 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holiday', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='payment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('card_name', models.TextField(blank=True, null=True)),
                ('card_no', models.TextField(blank=True, null=True)),
                ('date', models.TextField(blank=True, null=True)),
                ('cvv', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'payment',
                'managed': False,
            },
        ),
    ]
>>>>>>> 591af9b (Initial commit)
