<<<<<<< HEAD
# Generated by Django 4.2.8 on 2024-07-19 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holiday', '0002_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='IMAGE',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.TextField(blank=True, null=True)),
                ('title', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'image',
                'managed': False,
            },
        ),
    ]
=======
# Generated by Django 4.2.8 on 2024-07-19 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holiday', '0002_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='IMAGE',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.TextField(blank=True, null=True)),
                ('title', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'image',
                'managed': False,
            },
        ),
    ]
>>>>>>> 591af9b (Initial commit)
